name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint --ext .jsx --fix src
      
  test:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: vitest run

  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: echo "Deploying..."
